services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "81:8080"
    volumes:
      - .:/app
    restart: unless-stopped
